### PR TITLE
xof: Make the `SeedStreamAes128` constructor public

### PR DESCRIPTION
**Pull request by cjpatton**

### CODE REVIEW

**Review by divergentdave — APPROVED** [review]
Sounds good to me. It's strange that we had `SeedStreamAes128` public, but made constructing one impossible since removing `PrgAes128`.

**Comment by inahga** [comment]
n.b. looking at `SeedStreamSha3` and `SeedStreamFixedKeyAes128` they don't appear to be publicly constructable either.

**Comment by divergentdave** [comment]
Yes, those two aren't directly constructable, but they are produced by their respective Xof (née Prg) types, after hashing inputs.

**Comment by inahga** [comment]
Ah I see, I didn't catch that `SeedStreamAes128` didn't have a matching `Xof` type.

**Pull request merged**
